In [2]:
import pandas as pd
import numpy as np

In [3]:
terror = pd.read_csv("terror.csv", engine = "python")
terror

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,0,0,NaN,0,NaN,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,197000000002,1970,0,0,NaN,0,NaN,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,197001000001,1970,1,0,NaN,0,NaN,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
3,197001000002,1970,1,0,NaN,0,NaN,78,Greece,8,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
4,197001000003,1970,1,0,NaN,0,NaN,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
5,197001010002,1970,1,1,NaN,0,NaN,217,United States,1,...,"The Cairo Chief of Police, William Petersen, r...","""Police Chief Quits,"" Washington Post, January...","""Cairo Police Chief Quits; Decries Local 'Mili...","Christopher Hewitt, ""Political Violence and Te...",Hewitt Project,-9,-9,0,-9,NaN
6,197001020001,1970,1,2,NaN,0,NaN,218,Uruguay,3,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
7,197001020002,1970,1,2,NaN,0,NaN,217,United States,1,...,"Damages were estimated to be between $20,000-$...",Committee on Government Operations United Stat...,"Christopher Hewitt, ""Political Violence and Te...",NaN,Hewitt Project,-9,-9,0,-9,NaN
8,197001020003,1970,1,2,NaN,0,NaN,217,United States,1,...,The New Years Gang issue a communiqu√© to a loc...,"Tom Bates, ""Rads: The 1970 Bombing of the Army...","David Newman, Sandra Sutherland, and Jon Stewa...","The Wisconsin Cartographers' Guild, ""Wisconsin...",Hewitt Project,0,0,0,0,NaN
9,197001030001,1970,1,3,NaN,0,NaN,217,United States,1,...,"Karl Armstrong's girlfriend, Lynn Schultz, dro...",Committee on Government Operations United Stat...,"Tom Bates, ""Rads: The 1970 Bombing of the Army...","David Newman, Sandra Sutherland, and Jon Stewa...",Hewitt Project,0,0,0,0,NaN
10,197001050001,1970,1,1,NaN,0,NaN,217,United States,1,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
11,197001060001,1970,1,6,NaN,0,NaN,217,United States,1,...,NaN,Committee on Government Operations United Stat...,"Christopher Hewitt, ""Political Violence and Te...",NaN,Hewitt Project,-9,-9,0,-9,NaN
12,197001080001,1970,1,8,NaN,0,NaN,98,Italy,8,...,NaN,NaN,NaN,NaN,Hijacking DB,-9,-9,1,1,NaN
13,197001090001,1970,1,9,NaN,0,NaN,217,United States,1,...,NaN,Committee on Government Operations United Stat...,"Christopher Hewitt, ""Political Violence and Te...",NaN,Hewitt Project,-9,-9,0,-9,NaN
14,197001090002,1970,1,9,NaN,0,NaN,217,United States,1,...,The fire began at 8:30 PM. The Armed Commandos...,Committee on the Judiciary United States Sena...,"""No Evidence Of Arson Found In Barkers Fire,"" ...","""Toward People's War for Independence and Soci...",Hewitt Project,0,0,0,0,NaN
15,197001100001,1970,1,10,NaN,0,NaN,499,East Germany (GDR),9,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
16,197001110001,1970,1,11,NaN,0,NaN,65,Ethiopia,11,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
17,197001120001,1970,1,12,NaN,0,NaN,217,United States,1,...,"One half hour after the bomb explosion, an ano...","""Blast Damages Flatbush School,"" New York Time...","Linda Greenhouse, ""Madison School Puzzled By B...",Committee on Government Operations United Stat...,Hewitt Project,-9,-9,0,-9,NaN
18,197001120002,1970,1,12,NaN,0,NaN,217,United States,1,...,NaN,Committee on the Judiciary United States Sena...,"""Toward People's War for Independence and Soci...",NaN,Hewitt Project,-9,-9,0,-9,NaN
19,197001130001,1970,1,13,NaN,0,NaN,217,United States,1,...,The store was a White owned business operating...,Committee on Government Operations United Stat...,NaN,NaN,Hewitt Project,-9,-9,0,-9,NaN
20,197001140001,1970,1,14,NaN,0,NaN,217,United States,1,...,NaN,Committee on Government Operations United Stat...,"Christopher Hewitt, ""Political Violence and Te...","Peter F. Nardulli and Jeffrey M. Stonecash, ""P...",Hewitt Project,-9,-9,0,-9,NaN
21,197001150001,1970,1,15,NaN,0,NaN,218,Uruguay,3,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
22,197001190002,1970,1,19,NaN,0,NaN,217,United States,1,...,Witnesses observed three African American male...,Committee on Government Operations United Stat...,"Christopher Hewitt, ""Political Violence and Te...","Seattle University, ""1965-1975: Troubled Times...",Hewitt Project,-9,-9,0,-9,NaN
23,197001190003,1970,1,19,NaN,0,NaN,217,United States,1,...,Judith and Silas Bissell were both members of ...,Committee on Government Operations United Stat...,"Christopher Hewitt, ""Political Violence and Te...","Earl Caldwell, ""Fear Grows In Seattle As Polic...",Hewitt Project,-9,-9,0,-9,NaN
24,197001190004,1970,1,19,"January 19-20, 1970",0,NaN,217,United States,1,...,The building might have been shot at a second ...,Committee on Government Operations United Stat...,"""Black Panthers Say Office Was Bombed,"" New Yo...","""30 Shots Fired Into Office of Panthers in Jer...",Hewitt Project,-9,-9,0,-9,NaN
25,197001200001,1970,1,20,NaN,0,NaN,83,Guatemala,2,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
26,197001210001,1970,1,21,NaN,0,NaN,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
27,197001220001,1970,1,22,NaN,0,NaN,222,Venezuela,3,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
28,197001220002,1970,1,22,NaN,0,NaN,217,United States,1,...,This attack might be linked with other episode...,Committee on Government Operations United Stat...,"""Beef Plant Workers in Nebraska Await Call to ...",NaN,Hewitt Project,-9,-9,0,-9,NaN
29,197001250001,1970,1,25,NaN,0,NaN,217,United States,1,...,"Police, at the time suspected, that this attac...","""Miss. City Is Desegregation Trouble Spot,"" Ch...",NaN,NaN,Hewitt Project,-9,-9,0,-9,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156742,201512310002,2015,12,31,NaN,0,NaN,95,Iraq,10,...,NaN,"""Iraq: Roundup of Security Incidents 29 Decemb...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
156743,201512310004,2015,12,31,NaN,0,NaN,95,Iraq,10,...,NaN,"""Iraq: Roundup of Security Incidents 29 Decemb...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
156744,201512310005,2015,12,31,NaN,0,NaN,95,Iraq,10,...,NaN,"""8 people killed, wounded in bomb south west o...","""Iraq: Roundup of Security Incidents 29 Decemb...","""Terrorism: Transcript of ISIL's Al-Bayan Radi...",START Primary Collection,-9,-9,0,-9,NaN
156745,201512310006,2015,12,31,NaN,0,NaN,95,Iraq,10,...,NaN,"""7 people killed, wounded in bomb blast east o...","""Iraq: Security Roundup 1900 GMT 31 December 2...",NaN,START Primary Collection,-9,-9,0,-9,NaN
156746,201512310008,2015,12,31,NaN,1,NaN,228,Yemen,10,...,NaN,"""Aden army commander survives Yemen bombing,"" ...","""Yemen: Security Roundup 2000 GMT 31 December ...","""Gunmen kill senior militia leader in Yemen's ...",START Primary Collection,-9,-9,0,-9,NaN
156747,201512310009,2015,12,31,NaN,0,NaN,228,Yemen,10,...,NaN,"""Aden army commander survives Yemen bombing,"" ...","""Senior south Yemen army chief survives bombin...","""Senior south Yemen army commander survives bo...",START Primary Collection,-9,-9,0,-9,NaN
156748,201512310010,2015,12,31,NaN,0,NaN,228,Yemen,10,...,NaN,"""Yemen: Security Roundup 2000 GMT 31 December ...",NaN,NaN,START Primary Collection,0,1,0,1,NaN
156749,201512310012,2015,12,31,NaN,0,NaN,228,Yemen,10,...,NaN,"""Yemen: Security Roundup 2000 GMT 31 December ...",NaN,NaN,START Primary Collection,0,0,0,0,NaN
156750,201512310013,2015,12,31,NaN,0,NaN,173,Saudi Arabia,10,...,NaN,"""Saudi-led coalition ending Yemen ceasefire, s...","""Yemen: Security Roundup 2000 GMT 31 December ...",NaN,START Primary Collection,1,1,0,1,NaN
156751,201512310015,2015,12,31,NaN,0,NaN,60,Egypt,10,...,There is doubt that this incident meets terror...,"""Egypt parents, 3 children killed by shelling ...","""Egypt parents, three children killed by shell...","""Egypt officials: Militants in Sinai kill enti...",START Primary Collection,-9,-9,0,-9,NaN
156752,201512310016,2015,12,31,NaN,0,NaN,173,Saudi Arabia,10,...,NaN,"""Missile from Yemen kills 3 Saudi civilians,"" ...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
156753,201512310017,2015,12,31,NaN,0,NaN,155,West Bank and Gaza Strip,10,...,NaN,"""IDF soldier lightly wounded in West Bank ramm...","""Palestinian in West Bank rams Israeli forces ...","""Breaking: Soldier lightly wounded in vehicula...",START Primary Collection,0,0,0,0,NaN
156754,201512310018,2015,12,31,NaN,0,NaN,209,Turkey,10,...,NaN,"""Anadolu Agency Reports One PKK Member Killed,...",NaN,NaN,START Primary Collection,0,0,0,0,NaN
156755,201512310019,2015,12,31,NaN,0,NaN,214,Ukraine,9,...,NaN,"""Ukrainian Police Blame Second Crimean Power O...","""Ukrainian police say Crimean power line damag...","""Power transmission line tower in Kherson regi...",START Primary Collection,-9,-9,0,-9,NaN
156756,201512310020,2015,12,31,NaN,0,NaN,92,India,6,...,NaN,"""Grenade hurled at Police Station Khanyar,"" Ka...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
156757,201512310021,2015,12,31,NaN,0,NaN,75,Germany,8,...,NaN,"""1ST LEAD,"" Deutsche Presse-Agentur, January 1...",NaN,NaN,START Primary Collection,-9,-9,1,1,NaN
156758,201512310022,2015,12,31,NaN,0,NaN,65,Ethiopia,11,...,Casualty numbers for this incident conflict ac...,"""Students said leaving southern Ethiopian univ...","""Hand grenade attack kills 2 at Ethiopian univ...","""Hand grenade attack kills two at Ethiopian un...",START Primary Collection,-9,-9,0,-9,NaN
156759,201512310024,2015,12,31,NaN,0,NaN,160,Philippines,5,...,NaN,"""Philippines: BIFF launches simultaneous attac...","""BIFF harassments, rido disrupt New Year celeb...","""HeadlinesTroops beat back BIFF assaults on 3 ...",START Primary Collection,0,0,0,0,"201512310024, 201512310026, 201512310027"
156760,201512310025,2015,12,31,NaN,0,NaN,4,Afghanistan,6,...,NaN,"""Afghanistan: Unknown Gunmen Murder Girls' Sch...","""Highlights: Pakistan Pashto Press 2 January, ...",NaN,START Primary Collection,0,0,0,0,NaN
156761,201512310026,2015,12,31,NaN,0,NaN,160,Philippines,5,...,NaN,"""Philippines: BIFF launches simultaneous attac...","""BIFF harassments, rido disrupt New Year celeb...","""HeadlinesTroops beat back BIFF assaults on 3 ...",START Primary Collection,0,0,0,0,"201512310024, 201512310026, 201512310027"
156762,201512310027,2015,12,31,NaN,0,NaN,160,Philippines,5,...,Casualty numbers for this incident conflict ac...,"""26 BIFF rebels slain in attacks,"" Manila Time...","""Philippines: BIFF launches simultaneous attac...","""BIFF harassments, rido disrupt New Year celeb...",START Primary Collection,0,0,0,0,"201512310024, 201512310026, 201512310027"
156763,201512310028,2015,12,31,2015-12-31 00:00:00,0,NaN,95,Iraq,10,...,NaN,"""Bomb blast kills soldier, wounds another in s...","""2 soliders killed, wounded in explosion in so...",NaN,START Primary Collection,-9,-9,0,-9,NaN
156764,201512310029,2015,12,31,NaN,0,NaN,153,Pakistan,6,...,NaN,"""Unknown armed men fire 3 rockets in Mand and ...","""Highlights: Pakistan Balochistan Press 1 Janu...",NaN,START Primary Collection,-9,-9,0,-9,NaN
156765,201512310030,2015,12,31,NaN,0,NaN,153,Pakistan,6,...,NaN,"""Unknown armed men fire 3 rockets in Mand and ...","""Highlights: Pakistan Balochistan Press 1 Janu...",NaN,START Primary Collection,0,0,0,0,NaN
156766,201512310031,2015,12,31,NaN,0,NaN,153,Pakistan,6,...,NaN,"""Unknown armed men fire 3 rockets in Mand and ...","""Highlights: Pakistan Balochistan Press 1 Janu...",NaN,START Primary Collection,0,0,0,0,NaN
156767,201512310032,2015,12,31,NaN,0,NaN,34,Burundi,11,...,Casualty numbers for this incident conflict ac...,"""1 dead, dozens injured in Burundi grenade att...","""One dead, dozen hurt in Burundi grenade attac...",NaN,START Primary Collection,-9,-9,0,-9,NaN
156768,201512310033,2015,12,31,2015-12-31 00:00:00,0,NaN,96,Ireland,8,...,NaN,"""Garda√≠ investigate Knocknaheeny pipe bomb,"" C...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
156769,201512310034,2015,12,31,NaN,0,NaN,160,Philippines,5,...,NaN,"""Village official killed, 2 injured in Marawi,...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
156770,201512310036,2015,12,31,2015-12-31 00:00:00,0,NaN,182,Somalia,11,...,NaN,"""Africa Command OSINT Daily 31 December 2015,""...",NaN,NaN,START Primary Collection,0,0,0,0,NaN
156771,201512310037,2015,12,31,NaN,1,1/16/16,113,Libya,10,...,Casualty numbers for this attack conflict acro...,"""20 Egyptian captives return from Libya, one r...","""21 abducted nationals released in Libya,"" Cai...","""Libya Daily Digest January 20, 2016,"" Libya D...",START Primary Collection,0,1,1,1,NaN

In [4]:
list(terror)

['eventid',
 'iyear',
 'imonth',
 'iday',
 'approxdate',
 'extended',
 'resolution',
 'country',
 'country_txt',
 'region',
 'region_txt',
 'provstate',
 'city',
 'latitude',
 'longitude',
 'specificity',
 'vicinity',
 'location',
 'summary',
 'crit1',
 'crit2',
 'crit3',
 'doubtterr',
 'alternative',
 'alternative_txt',
 'multiple',
 'success',
 'suicide',
 'attacktype1',
 'attacktype1_txt',
 'attacktype2',
 'attacktype2_txt',
 'attacktype3',
 'attacktype3_txt',
 'targtype1',
 'targtype1_txt',
 'targsubtype1',
 'targsubtype1_txt',
 'corp1',
 'target1',
 'natlty1',
 'natlty1_txt',
 'targtype2',
 'targtype2_txt',
 'targsubtype2',
 'targsubtype2_txt',
 'corp2',
 'target2',
 'natlty2',
 'natlty2_txt',
 'targtype3',
 'targtype3_txt',
 'targsubtype3',
 'targsubtype3_txt',
 'corp3',
 'target3',
 'natlty3',
 'natlty3_txt',
 'gname',
 'gsubname',
 'gname2',
 'gsubname2',
 'gname3',
 'ingroup',
 'ingroup2',
 'ingroup3',
 'gsubname3',
 'motive',
 'guncertain1',
 'guncertain2',
 'guncertain3',
 'nperps',
 'nperpcap',
 'claimed',
 'claimmode',
 'claimmode_txt',
 'claim2',
 'claimmode2',
 'claimmode2_txt',
 'claim3',
 'claimmode3',
 'claimmode3_txt',
 'compclaim',
 'weaptype1',
 'weaptype1_txt',
 'weapsubtype1',
 'weapsubtype1_txt',
 'weaptype2',
 'weaptype2_txt',
 'weapsubtype2',
 'weapsubtype2_txt',
 'weaptype3',
 'weaptype3_txt',
 'weapsubtype3',
 'weapsubtype3_txt',
 'weaptype4',
 'weaptype4_txt',
 'weapsubtype4',
 'weapsubtype4_txt',
 'weapdetail',
 'nkill',
 'nkillus',
 'nkillter',
 'nwound',
 'nwoundus',
 'nwoundte',
 'property',
 'propextent',
 'propextent_txt',
 'propvalue',
 'propcomment',
 'ishostkid',
 'nhostkid',
 'nhostkidus',
 'nhours',
 'ndays',
 'divert',
 'kidhijcountry',
 'ransom',
 'ransomamt',
 'ransomamtus',
 'ransompaid',
 'ransompaidus',
 'ransomnote',
 'hostkidoutcome',
 'hostkidoutcome_txt',
 'nreleased',
 'addnotes',
 'scite1',
 'scite2',
 'scite3',
 'dbsource',
 'INT_LOG',
 'INT_IDEO',
 'INT_MISC',
 'INT_ANY',
 'related']

In [117]:
# 1.How many attacks happened in India?

len(terror.query("country_txt == 'India'"))

9908

In [5]:
# 2.How many attacks happened in India and upto 3 people were killed? 

len(terror[(terror.country_txt == 'India') & (terror.nkill <= 3)])

8362

In [40]:
# 3.Extract the city and summary for attacks above

terror[(terror.country_txt == 'India') & (terror.nkill <= 3)][["city","summary"]]

                     city                                            summary
1185            New Delhi                                                NaN
3780            New Delhi                                                NaN
5251               Bombay                                                NaN
7266               Imphal                                                NaN
8609              Unknown                                                NaN
8755              Unknown                                                NaN
8977               Amapur                                                NaN
9037             Raisikah                                                NaN
9040             Champhai                                                NaN
9070               Aizawl                                                NaN
9072           Jamshedpur                                                NaN
9081            New Delhi                                                NaN
9082            New Delhi                                                NaN
9090           Jamshedpur                                                NaN
9137              Chennai                                                NaN
9691              Unknown                                                NaN
9732              Unknown                                                NaN
9801              Unknown                                                NaN
9841               Imphal                                                NaN
9887              Unknown                                                NaN
10407           Chiaplant                                                NaN
10522            Calcutta                                                NaN
10744           New Delhi                                                NaN
12187             Unknown                                                NaN
12391             Unknown                                                NaN
12439             Unknown                                                NaN
13049             Gauhati                                                NaN
13177              Jorhat                                                NaN
13300             Unknown                                                NaN
13875             Unknown                                                NaN
...                   ...                                                ...
156156         Dariyakona  12/15/2015: Assailants abducted Baghel Gond fr...
156176           Awapalli  12/15/2015: An explosive device detonated in A...
156243           Srinagar  12/17/2015: Assailants fired a rifle grenade a...
156248             Imphal  12/17/2015: An explosive device detonated in D...
156249       Williamnagar  12/17/2015: Assailants threw a grenade at a st...
156292     Pookottumpadam  12/18/2015: Assailants attacked an Indian Fore...
156314        Kalia Atala  12/19/2015: Assailants torched an Airtel cell ...
156339           Chipakur  12/20/2015: Assailants torched an under-constr...
156340            Kakpora  12/20/2015: Assailants threw a grenade at the ...
156383    Bastar district  12/21/2015: Security forces arrested three ass...
156384       Madathakonda  12/21/2015: Assailants abducted and killed Van...
156385       Madathakonda  12/21/2015: Assailants beat a civilian in Mada...
156388       Badapokharia  12/21/2015: Assailants threw at least nine cru...
156389      Simra Nizamat  12/21/2015: Police discovered and defused two ...
156433             Imphal  12/22/2015: Assailants shot and killed a baker...
156458           Nilawaya  12/23/2015: Assailants abducted Hadma Ram, a f...
156459             Imphal  12/23/2015: An explosive device planted under ...
156483          Bijbehara  12/24/2015: Assailants opened fire on police p...
156499            Ramgarh  12/24/2015: Assailants detonated explosive dev...
156529          Badapadar  12/25/2015: Assailants attacked Jayaram Khara ...
156530  Kudumulgumma Raba  12/25/2015: Assailants attacked Sahdev Badanay...
156533          Sivasagar  12/25/2015: Security forces discovered and def...
156569             Pariya  12/26/2015: Assailants abducted Sujit Modiyami...
156612           Tillayya  12/26/2015: An assailant attempted to plant an...
156658            Mendhar  12/27/2015: An explosive device planted under ...
156695              Terem  12/29/2015: Assailants abducted three students...
156698         Peravurani  12/29/2015: An explosive device was discovered...
156713          Tulsibari  12/29/2015: Assailants abducted Hazrat Ali in ...
156725            Zhutovi  12/30/2015: Assailants attempted to extort mon...
156756           Srinagar  12/31/2015: Assailants threw a grenade at an I...

[8362 rows x 2 columns]

In [44]:
# 4.In a single terror incident in India, find out top 5 cities by number killed

terror[(terror.nperps == 1) & (terror.country_txt == 'India')].sort_values('nkill',ascending = False)["city"].head(5)

46445    Sriperumpudur
76305              Uri
76296          Pulwama
78444         Srinagar
75204           Poonch
Name: city, dtype: object

In [72]:
# 5.In a single terror incident in India, find out top 5 cities by number killed and wounded 


terror["kill_wound"] = terror.nkill + terror.nwound
terror[(terror.nperps == 1) & (terror.country_txt == 'India')].sort_values('kill_wound',ascending = False)["city"].head()

76296      Pulwama
75609      Shopian
73364    Bandipora
65591      Pulwama
76305          Uri
Name: city, dtype: object

In [74]:
# 6.How many attacks were successful that were suicide attacks?

len(terror[(terror.success == 1) & (terror.suicide == 1)])

4260

In [94]:
# 7.label all the incidents where the number killed was more than 5 as severe

terror["severe"] = np.nan
terror.loc[terror.nkill > 5, "severe"] = "severe"
print(terror.severe)

0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12           NaN
13           NaN
14           NaN
15           NaN
16           NaN
17           NaN
18           NaN
19           NaN
20           NaN
21           NaN
22           NaN
23           NaN
24           NaN
25           NaN
26           NaN
27           NaN
28           NaN
29           NaN
           ...
156742       NaN
156743       NaN
156744       NaN
156745       NaN
156746       NaN
156747       NaN
156748       NaN
156749       NaN
156750       NaN
156751       NaN
156752       NaN
156753       NaN
156754       NaN
156755       NaN
156756       NaN
156757       NaN
156758       NaN
156759       NaN
156760       NaN
156761       NaN
156762    severe
156763       NaN
156764       NaN
156765       NaN
156766       NaN
156767       NaN
156768       NaN
156769       NaN
156770       NaN
156771       NaN
Name: severe, Length: 156772, dtype: object

In [112]:
# 8.write a function to label an incident that was both successful and suicidal

def incident():
    terror.loc[(terror.success == 1) & (terror.suicide == 1), "severe"] = "incident"
    
incident()

array([nan, 'severe', 'incident'], dtype=object)

In [14]:
# 9.Create a new category representing if the incident occured in Afghanistan, 
# Pakistan or India as one level of the category and all the other countries as another level

terror["category_new"] = np.nan
API = ["Afganisthan","Pakistan","India"]
terror.loc[terror.country_txt.isin(API), "category_new"] = "Asia" 
terror.loc[~(terror.country_txt.isin(API)),"category_new"] = "rest_countries"
terror["category_new"]

0         rest_countries
1         rest_countries
2         rest_countries
3         rest_countries
4         rest_countries
5         rest_countries
6         rest_countries
7         rest_countries
8         rest_countries
9         rest_countries
10        rest_countries
11        rest_countries
12        rest_countries
13        rest_countries
14        rest_countries
15        rest_countries
16        rest_countries
17        rest_countries
18        rest_countries
19        rest_countries
20        rest_countries
21        rest_countries
22        rest_countries
23        rest_countries
24        rest_countries
25        rest_countries
26        rest_countries
27        rest_countries
28        rest_countries
29        rest_countries
               ...
156742    rest_countries
156743    rest_countries
156744    rest_countries
156745    rest_countries
156746    rest_countries
156747    rest_countries
156748    rest_countries
156749    rest_countries
156750    rest_countries
156751    rest_countries
156752    rest_countries
156753    rest_countries
156754    rest_countries
156755    rest_countries
156756              Asia
156757    rest_countries
156758    rest_countries
156759    rest_countries
156760    rest_countries
156761    rest_countries
156762    rest_countries
156763    rest_countries
156764              Asia
156765              Asia
156766              Asia
156767    rest_countries
156768    rest_countries
156769    rest_countries
156770    rest_countries
156771    rest_countries
Name: category_new, Length: 156772, dtype: object

In [15]:
# 10.How many incidents happened in Af-Pak-India vs ROW?

terror["category_new"].value_counts()

rest_countries    134064
Asia               22708
Name: category_new, dtype: int64

In [17]:
# 11.List the number of suicides attacks and average kills by Af-Pak-India vs ROW. 
# Rename columns in the output as Average_Kills and Number_Incidents.

pd.crosstab(terror.category_new,terror.suicide,colnames = ["Number_Incidents"])
df = terror.groupby("category_new")["nkill"].mean().reset_index()
df.columns = ["category","Average_kills"]
df

         category  Average_kills
0            Asia       1.788422
1  rest_countries       2.460740